package com.example.smartcare.City

// Create a new file: CityData.kt
val karnatakaCities = listOf(
    "Bagalkot, Bagalkot, Karnataka",
    "Badami, Bagalkot, Karnataka",
    "Ilkal, Bagalkot, Karnataka",
    "Jamkhandi, Bagalkot, Karnataka",
    "Mudhol, Bagalkot, Karnataka",
    "Bengaluru, Bengaluru Urban, Karnataka",
    "Devanahalli, Bengaluru Rural, Karnataka",
    "Doddaballapura, Bengaluru Rural, Karnataka",
    "Hoskote, Bengaluru Rural, Karnataka",
    "Nelamangala, Bengaluru Rural, Karnataka",
    "Belagavi, Belagavi, Karnataka",
    "Athani, Belagavi, Karnataka",
    "Chikodi, Belagavi, Karnataka",
    "Gokak, Belagavi, Karnataka",
    "Nipani, Belagavi, Karnataka",
    "Ramdurg, Belagavi, Karnataka",
    "Saundatti, Belagavi, Karnataka",
    "Ballari, Ballari, Karnataka",
    "Hospet, Ballari, Karnataka",
    "Sandur, Ballari, Karnataka",
    "Bidar, Bidar, Karnataka",
    "Basavakalyan, Bidar, Karnataka",
    "Bhalki, Bidar, Karnataka",
    "Vijayapura, Vijayapura, Karnataka",
    "Basavana Bagevadi, Vijayapura, Karnataka",
    "Sindagi, Vijayapura, Karnataka",
    "Chamarajanagar, Chamarajanagar, Karnataka",
    "Gundlupet, Chamarajanagar, Karnataka",
    "Kollegal, Chamarajanagar, Karnataka",
    "Chikballapur, Chikballapur, Karnataka",
    "Chintamani, Chikballapur, Karnataka",
    "Sidlaghatta, Chikballapur, Karnataka",
    "Chikkamagaluru, Chikkamagaluru, Karnataka",
    "Kadur, Chikkamagaluru, Karnataka",
    "Mudigere, Chikkamagaluru, Karnataka",
    "Tarikere, Chikkamagaluru, Karnataka",
    "Chitradurga, Chitradurga, Karnataka",
    "Hiriyur, Chitradurga, Karnataka",
    "Hosadurga, Chitradurga, Karnataka",
    "Mangaluru, Dakshina Kannada, Karnataka",
    "Bantwal, Dakshina Kannada, Karnataka",
    "Puttur, Dakshina Kannada, Karnataka",
    "Moodabidri, Dakshina Kannada, Karnataka",
    "Sulya, Dakshina Kannada, Karnataka",
    "Davanagere, Davanagere, Karnataka",
    "Harihar, Davanagere, Karnataka",
    "Channagiri, Davanagere, Karnataka",
    "Hubballi, Dharwad, Karnataka",
    "Dharwad, Dharwad, Karnataka",
    "Navalgund, Dharwad, Karnataka",
    "Kundgol, Dharwad, Karnataka",
    "Gadag-Betageri, Gadag, Karnataka",
    "Mundargi, Gadag, Karnataka",
    "Nargund, Gadag, Karnataka",
    "Ron, Gadag, Karnataka",
    "Kalaburagi, Kalaburagi, Karnataka",
    "Afzalpur, Kalaburagi, Karnataka",
    "Sedam, Kalaburagi, Karnataka",
    "Chincholi, Kalaburagi, Karnataka",
    "Hassan, Hassan, Karnataka",
    "Arsikere, Hassan, Karnataka",
    "Sakleshpur, Hassan, Karnataka",
    "Channarayapatna, Hassan, Karnataka",
    "Haveri, Haveri, Karnataka",
    "Ranibennur, Haveri, Karnataka",
    "Savanur, Haveri, Karnataka",
    "Hirekerur, Haveri, Karnataka",
    "Madikeri, Kodagu, Karnataka",
    "Somwarpet, Kodagu, Karnataka",
    "Virajpet, Kodagu, Karnataka",
    "Kolar, Kolar, Karnataka",
    "Malur, Kolar, Karnataka",
    "Mulbagal, Kolar, Karnataka",
    "Yadgir, Yadgir, Karnataka",
    "Shahpur, Yadgir, Karnataka",
    "Shorapur, Yadgir, Karnataka",
    "Karwar, Uttara Kannada, Karnataka",
    "Dandeli, Uttara Kannada, Karnataka",
    "Sirsi, Uttara Kannada, Karnataka",
    "Bhatkal, Uttara Kannada, Karnataka",
    "Kumta, Uttara Kannada, Karnataka",
    "Udupi, Udupi, Karnataka",
    "Kundapura, Udupi, Karnataka",
    "Karkala, Udupi, Karnataka",
    "Tumakuru, Tumakuru, Karnataka",
    "Tiptur, Tumakuru, Karnataka",
    "Gubbi, Tumakuru, Karnataka",
    "Madhugiri, Tumakuru, Karnataka",
    "Shivamogga, Shivamogga, Karnataka",
    "Bhadravati, Shivamogga, Karnataka",
    "Sagara, Shivamogga, Karnataka",
    "Tirthahalli, Shivamogga, Karnataka",
    "Channapatna, Ramanagara, Karnataka",
    "Kanakapura, Ramanagara, Karnataka",
    "Ramanagara, Ramanagara, Karnataka",
    "Mandya, Mandya, Karnataka",
    "Maddur, Mandya, Karnataka",
    "Malavalli, Mandya, Karnataka",
    "K.R. Pet, Mandya, Karnataka",
    "Mysuru, Mysuru, Karnataka",
    "Nanjangud, Mysuru, Karnataka",
    "Hunsur, Mysuru, Karnataka",
    "T. Narasipura, Mysuru, Karnataka",
    "Raichur, Raichur, Karnataka",
    "Manvi, Raichur, Karnataka",
    "Sindhanur, Raichur, Karnataka",
    "Koppal, Koppal, Karnataka",
    "Gangavathi, Koppal, Karnataka",
    "Yelburga, Koppal, Karnataka",
    "Anekal, Bengaluru Urban, Karnataka",
    "Ankola, Uttara Kannada, Karnataka",
    "Bagepalli, Chikballapur, Karnataka",
    "Bailhongal, Belagavi, Karnataka",
    "Banavar, Hassan, Karnataka",
    "Basavana Bagewadi, Vijayapura, Karnataka",
    "Bellary, Ballari, Karnataka",
    "Bijapur, Vijayapura, Karnataka",
    "Bilgi, Bagalkot, Karnataka",
    "Birur, Chikkamagaluru, Karnataka",
    "Byadagi, Haveri, Karnataka",
    "Byndoor, Udupi, Karnataka",
    "Challakere, Chitradurga, Karnataka",
    "Chamrajnagar, Chamarajanagar, Karnataka",
    "Chik Ballapur, Chikballapur, Karnataka",
    "Chikkaballapur, Chikballapur, Karnataka",
    "Chikmagalur, Chikkamagaluru, Karnataka",
    "Chiknayakanhalli, Tumakuru, Karnataka",
    "Chikodi, Belagavi, Karnataka",
    "Hubli-Dharwad, Dharwad, Karnataka",
    "Robertsonpet, Kolar, Karnataka",
    "Hospet, Vijayanagara, Karnataka",
    "Haliyal, Dharwad, Karnataka"
)

val parsedCities = parseCities(karnatakaCities)
